---
ID: "ecb47dd1-8390-4551-9edd-ea680b7466e2"
Parent: "68dc89a4-1b04-59a8-9c4e-3b49d6c61052"
Template: "d8aa73e1-c275-4eee-bb9d-333925e51952"
Path: /sitecore/content/EdgeWebsite/home/sessions/Train smarter not harder
SharedFields:
- ID: "9b0343a9-9f69-4e0f-a059-9215bc8fe422"
  Hint: EntityIdentifier
  Value: HOl1YUjfoEScb2gWsvJGZA
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "21df785e-14dd-4c8d-abff-5ae00b693e5e"
      Hint: Description
      Value: |
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
             
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210919T091145Z
    - ID: "3647d085-16e3-44ee-a3f7-c613d0fe17ce"
      Hint: Speakers
      Value: "{E17D2423-B3CC-48DF-93B5-CB108E9DB4A1}"
    - ID: "51084853-806c-4e3d-90a3-0eaec3faa3ac"
      Hint: Day
      Value: Day 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        default\Anonymous
    - ID: "5c88d198-7603-4a45-b9f6-682b908c60b9"
      Hint: Timeslots
      Value: "{AC91E010-BC61-4C83-8786-E8BF046171DB}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        default\Anonymous
    - ID: "6f888071-3e3a-4888-ae95-d90b7df06870"
      Hint: Type
      Value: Session
    - ID: "8058e5a0-d20d-4923-b87d-f56b19efc20f"
      Hint: Name
      Value: Train smarter, not harder
    - ID: "8c3dff8b-74bc-4a65-af6d-81452a3d9a11"
      Hint: Rooms
      Value: "{943C6051-66CF-44D8-9FF3-5A5CCED4AD35}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dd06d9cb-3357-48c7-9026-f644bfc33b37"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        default\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210922T144316Z
