# Build Sitecoredemo Docker images
trigger:
  branches:
    include:
    - develop

resources:
- repo: self
  clean: true

variables:
  GitVersion.SemVer: ''
  SITECORE_VERSION: '10.1.0'
  GitVersion.PreReleaseLabel: ''
  tag: '$(GitVersion.SemVer)'
  additionalImageTags: ''

stages:
- stage: Docker_Windows
  displayName: "Build Windows Images"
  jobs:
  - job: Build_Headless
    timeoutInMinutes: 120
    strategy:
      matrix:
        windows2004:
          poolName: 'docker-2004-agents'
          osVersion: '2004'
        ltsc2019:
          poolName: 'docker-ltsc2019-agents'
          osVersion: 'ltsc2019'
        20H2:
          poolName: 'docker-20H2-agents'
          osVersion: '20H2'
    displayName: 'Build Windows Docker Images'
    pool:
      name: $(poolName)
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
        installationPath: 'c:/program files/dotnet'
        performMultiLevelLookup: true
    - template: version.yml
    - task: PowerShell@2
      displayName: "Build and Push Images"
      inputs:
        targetType: 'inline'
        script: |
          $sitecoreRegistry = "$(sitecore.container.registry)"

          if ("$sitecoreRegistry" -ne "scr.sitecore.com/"){
            az login -u "$(sitecore.container.registry.username)" -p "$(sitecore.container.registry.password)" -t "$(sitecore.container.registry.tenant)"
            az acr login -n "$(sitecore.container.registry.short)"
          }

          az acr login -n $(container.registry.short)

          $params = @{}
          $params.Add("DemoVersion", "$(tag)")
          $params.Add("DemoTeamRegistry","$(REGISTRY)")
          $params.Add("SitecoreRegistry","$sitecoreRegistry")
          $params.Add("IsolationMode","process")
          $params.Add("WindowsVersion","$(osVersion)")
          $params.Add("SitecoreVersion","$(SITECORE_VERSION)")

          ./init-ci.ps1 @params

          # Reset demo version to correct tag without build id
          $env:DEMO_VERSION = "$(tag)"

          docker-compose build --parallel $(no.cache)
          docker-compose push

          $primaryBuild = $(if ([string]::IsNullOrEmpty("$(additionalImageTags)")) { $false } else { $true })
          if ($primaryBuild) {
            $env:DEMO_VERSION = "$(additionalImageTags)"
            docker-compose build --parallel
            docker-compose push
          }